apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rzsg3ctup-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rzsg3ctup-java-springboot-gitops